.mvn_build:
  dependencies: [] # 不会下载之前阶段的任何工件
  stage: package
  tags:
    - package
  script:
    - 'id && printenv'
    - $BUILD_SHELL
  after_script:
    - ls ${CACHE_DIR}
  variables:
    CI_DEBUG_TRACE: "false" # true表示调试
    GIT_CHECKOUT: "true" #表示当前阶段拉取代码,每个作业在开始的时候都会默认拉远程分支并清空构建目录,所有只需要在每个阶段拉代码即可
  artifacts:
    name: '$ARTIFACTS_NAME'
    when: on_success
    expire_in: 30 days
    paths:
      - ${ARTIFACTS}*.jar
  cache:
    policy: push # pull和push的含义是反着的，当策略为pull时意味着当前job开始的时候不会下载缓存,push则表示job结束时不会上传,默认是pull-push
    key: package
    paths:
      - ${CACHE_DIR}
